import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/navbar";
import ToastProvider from "@/components/toast.provider";

export const metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <Navbar />
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
